# ФАЙЛ ДЛЯ ЛОКАЛЬНОЙ РАЗРАБОТКИ
version: '3.8'
services:
  db:
    image: 'postgres:15.3'
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devdb
      - POSTGRES_PASSWORD=devdb
      - POSTGRES_DB=devdb

networks:
  dev_db:
    external: true
